//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etapy_w_procesie
    {
        public int ID_Proces_technologiczny { get; set; }
        public int ID_Etapu { get; set; }
        public int Czas { get; set; }
    
        public virtual Rodzaj_etapu Rodzaj_etapu { get; set; }
        public virtual Proces_technologiczny Proces_technologiczny { get; set; }
    }
}
