//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrola_efektywnosci
    {
        public int ID_procesu_produkcyjnego { get; set; }
        public System.DateTime Data_Kontroli { get; set; }
        public byte[] Dokument { get; set; }
        public string Uwagi { get; set; }
        public bool Zgodnosc_zamowienia { get; set; }
        public int Liczba_poprawnych { get; set; }
        public int Liczba_blednych { get; set; }
    
        public virtual Proces_Produkcyjny Proces_Produkcyjny { get; set; }
    }
}
