//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koszt_jednostkowy
    {
        public Nullable<int> ID_element { get; set; }
        public int Koszt_produkcji { get; set; }
    
        public virtual Magazyn_elementy Magazyn_elementy { get; set; }
    }
}
