//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_oferta
    {
        public string ID_oferta { get; set; }
        public Nullable<int> ID_element { get; set; }
        public string ID_dostawcy { get; set; }
        public Nullable<decimal> Cena_jedn { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public string Data_oferty { get; set; }
        public Nullable<int> Ilosc_minimalna { get; set; }
        public Nullable<int> Ilosc_maksymalna { get; set; }
        public Nullable<int> Ilosc_w_opakowaniu_zbiorczym { get; set; }
    
        public virtual Magazyn_dostawcy_zaopatrzenie Magazyn_dostawcy_zaopatrzenie { get; set; }
        public virtual Magazyn_elementy Magazyn_elementy { get; set; }
    }
}
