//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_kurierzy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magazyn_kurierzy()
        {
            this.Magazyn_umowy_kurierzy = new HashSet<Magazyn_umowy_kurierzy>();
        }
    
        public string ID_kurier { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Telefon_1 { get; set; }
        public Nullable<int> Telefon_2 { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magazyn_umowy_kurierzy> Magazyn_umowy_kurierzy { get; set; }
    }
}
