//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_polki
    {
        public string ID_polka { get; set; }
        public string ID_rozmiar_polki { get; set; }
    
        public virtual Magazyn_polki_rozmiary Magazyn_polki_rozmiary { get; set; }
    }
}
