//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_elementy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magazyn_elementy()
        {
            this.Czesci_obsluga = new HashSet<Czesci_obsluga>();
            this.Elementy_proces = new HashSet<Elementy_proces>();
            this.Koszt_jednostkowy = new HashSet<Koszt_jednostkowy>();
            this.Magazyn_oferta = new HashSet<Magazyn_oferta>();
            this.Material_na_produkcji = new HashSet<Material_na_produkcji>();
            this.Zamowienie_produkt = new HashSet<Zamowienie_produkt>();
            this.Zapotrzebowanie_opakowan = new HashSet<Zapotrzebowanie_opakowan>();
        }
    
        public int ID_element { get; set; }
        public Nullable<int> ID_Element_typ { get; set; }
        public string Element_nazwa { get; set; }
        public string Element_oznaczenie { get; set; }
        public Nullable<int> Okres_przydatnosci_miesiace { get; set; }
        public Nullable<float> Element_ilosc_w_paczce { get; set; }
        public Nullable<int> ID_jednostka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Czesci_obsluga> Czesci_obsluga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elementy_proces> Elementy_proces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Koszt_jednostkowy> Koszt_jednostkowy { get; set; }
        public virtual Magazyn_elementy_typy Magazyn_elementy_typy { get; set; }
        public virtual Magazyn_elementy_jednostki Magazyn_elementy_jednostki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magazyn_oferta> Magazyn_oferta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_na_produkcji> Material_na_produkcji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_produkt> Zamowienie_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapotrzebowanie_opakowan> Zapotrzebowanie_opakowan { get; set; }
    }
}
