//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maszyny_proces
    {
        public int ID_Proces_technologiczny { get; set; }
        public int ID_Rodzaj_maszyny { get; set; }
        public int Liczba { get; set; }
        public int Liczba_rbh { get; set; }
    
        public virtual Proces_technologiczny Proces_technologiczny { get; set; }
        public virtual Rodzaj_maszyny Rodzaj_maszyny { get; set; }
    }
}
