//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obsluga_techniczna
    {
        public int ID_Obslugi { get; set; }
        public int ID_Maszyny { get; set; }
        public int ID_Rodzaj_obslugi { get; set; }
        public System.DateTime Data_wykonania { get; set; }
        public int ID_Pracownika { get; set; }
    
        public virtual Czesci_obsluga Czesci_obsluga { get; set; }
        public virtual Maszyny Maszyny { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rodzaj_obslugi Rodzaj_obslugi { get; set; }
    }
}
