//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienia()
        {
            this.Faktury = new HashSet<Faktury>();
            this.Magazyn_dostarczenia_zewn = new HashSet<Magazyn_dostarczenia_zewn>();
            this.Magazyn_zamowienia_dostawy = new HashSet<Magazyn_zamowienia_dostawy>();
            this.Proces_Produkcyjny = new HashSet<Proces_Produkcyjny>();
            this.Proces_zamowienie = new HashSet<Proces_zamowienie>();
            this.Zamowienie_produkt = new HashSet<Zamowienie_produkt>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Klienta { get; set; }
        public Nullable<System.DateTime> Data_zlozenia { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia { get; set; }
        public Nullable<bool> Dokumentacja { get; set; }
        public Nullable<int> ID_Pracownika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magazyn_dostarczenia_zewn> Magazyn_dostarczenia_zewn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magazyn_zamowienia_dostawy> Magazyn_zamowienia_dostawy { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_Produkcyjny> Proces_Produkcyjny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_zamowienie> Proces_zamowienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_produkt> Zamowienie_produkt { get; set; }
    }
}
