//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czesci_obsluga
    {
        public int ID_Obslugi { get; set; }
        public int ID_Czesci { get; set; }
        public int Ilosc { get; set; }
    
        public virtual Magazyn_elementy Magazyn_elementy { get; set; }
        public virtual Obsluga_techniczna Obsluga_techniczna { get; set; }
    }
}
