//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumentacje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dokumentacje()
        {
            this.Dokumentacja_proces = new HashSet<Dokumentacja_proces>();
        }
    
        public int ID_Dokumentacji { get; set; }
        public int ID_Rodzaj { get; set; }
        public int ID_Pracownika { get; set; }
        public System.DateTime Data_wykonania { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokumentacja_proces> Dokumentacja_proces { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rodzaj_dokumentacji Rodzaj_dokumentacji { get; set; }
    }
}
