//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elementy_proces
    {
        public int ID_Proces_technologiczny { get; set; }
        public int ID_Elementu { get; set; }
        public int Liczba { get; set; }
    
        public virtual Magazyn_elementy Magazyn_elementy { get; set; }
        public virtual Proces_zamowienie Proces_zamowienie { get; set; }
    }
}
