//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_umowy_kurierzy
    {
        public int ID_umowy { get; set; }
        public string ID_kurier { get; set; }
        public Nullable<System.DateTime> Data_zawarcia { get; set; }
        public Nullable<System.TimeSpan> Czas_dostawy { get; set; }
        public Nullable<int> Koszt_km { get; set; }
        public Nullable<int> Koszt_staly { get; set; }
    
        public virtual Magazyn_kurierzy Magazyn_kurierzy { get; set; }
    }
}
