//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn_zamowienia_dostawy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magazyn_zamowienia_dostawy()
        {
            this.Magazyn_dostarczenia_wewn = new HashSet<Magazyn_dostarczenia_wewn>();
        }
    
        public int ID_dostawy { get; set; }
        public Nullable<int> ID_zamowienia { get; set; }
        public string Data_dostawy_planowana { get; set; }
        public string Data_dostawy_rzeczywista { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magazyn_dostarczenia_wewn> Magazyn_dostarczenia_wewn { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
