//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces_technologiczny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proces_technologiczny()
        {
            this.Proces_Produkcyjny = new HashSet<Proces_Produkcyjny>();
        }
    
        public int ID_Proces_technologiczny { get; set; }
        public int ID_Dokumentacja_proces { get; set; }
        public int ID_Pracownika { get; set; }
    
        public virtual Dokumentacja_proces Dokumentacja_proces { get; set; }
        public virtual Etapy_w_procesie Etapy_w_procesie { get; set; }
        public virtual Maszyny_proces Maszyny_proces { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_Produkcyjny> Proces_Produkcyjny { get; set; }
        public virtual Proces_zamowienie Proces_zamowienie { get; set; }
    }
}
