//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces_Produkcyjny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proces_Produkcyjny()
        {
            this.Kontrola_efektywnosci = new HashSet<Kontrola_efektywnosci>();
            this.Material_na_produkcji = new HashSet<Material_na_produkcji>();
            this.Realizacja_procesu = new HashSet<Realizacja_procesu>();
            this.Zapotrzebowanie_opakowan = new HashSet<Zapotrzebowanie_opakowan>();
        }
    
        public int ID_procesu_produkcyjnego { get; set; }
        public int ID_zamowienia { get; set; }
        public int ID_Proces_technologiczny { get; set; }
        public Nullable<System.DateTime> Data_rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia { get; set; }
        public Nullable<int> ID_Dokumentacji_proces { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Dokumentacja_proces Dokumentacja_proces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrola_efektywnosci> Kontrola_efektywnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_na_produkcji> Material_na_produkcji { get; set; }
        public virtual Proces_technologiczny Proces_technologiczny { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realizacja_procesu> Realizacja_procesu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapotrzebowanie_opakowan> Zapotrzebowanie_opakowan { get; set; }
    }
}
