//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realizacja_procesu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Realizacja_procesu()
        {
            this.Przydzial_zasobow = new HashSet<Przydzial_zasobow>();
        }
    
        public int ID_realizacji_procesu { get; set; }
        public int ID_procesu_produkcyjnego { get; set; }
        public int ID_etapu { get; set; }
        public System.DateTime Data_rozpoczecia_procesu { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia_procesu { get; set; }
        public Nullable<System.DateTime> Data_kontroli { get; set; }
        public string Uwagi_kontroli { get; set; }
    
        public virtual Proces_Produkcyjny Proces_Produkcyjny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przydzial_zasobow> Przydzial_zasobow { get; set; }
        public virtual Rodzaj_etapu Rodzaj_etapu { get; set; }
    }
}
