//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapotrzebowanie_opakowan
    {
        public int ID_procesu_produkcyjnego { get; set; }
        public int ID_element { get; set; }
        public int Liczba { get; set; }
        public Nullable<bool> Czy_otrzymano { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Magazyn_elementy Magazyn_elementy { get; set; }
        public virtual Proces_Produkcyjny Proces_Produkcyjny { get; set; }
    }
}
